apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: article-sts
  namespace: ams-backend
spec:
  selector:
    matchLabels:
      app: article
  serviceName: "article"
  replicas: 1
  template:
    metadata:
      labels:
        app: article
    spec:
      containers:
        - name: article
          image: sipacademy2024/servicearticle
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: database-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: database-password
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: database-cm
                  key: article_database_url
            - name: EUREKA_SERVICE_URL # This overrides your Spring Property
              valueFrom:
                configMapKeyRef:
                  name: eureka-cm
                  key: eureka_service_address
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"

---
apiVersion: v1
kind: Service
metadata:
  name: article-svc
  namespace: ams-backend
spec:
  clusterIP: None
  selector:
    app: provider
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
