apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-pvc-dynamic
  namespace: ams-backend
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path