apiVersion: v1
kind: ConfigMap
metadata:
  name: database-cm
data:
  provider_database_url: jdbc:mysql://mysql-svc:3306/bdServiceProviderAvril2024?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
  article_database_url: jdbc:mysql://mysql-svc:3306/bdServiceArticleAvril2024?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
