# eureka
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eureka
  namespace: ams-backend
spec:
  serviceName: "eureka"
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka
          image: sipacademy2024/serviceregistry
          imagePullPolicy: Always
          ports:
            - containerPort: 8761
          env:
            - name: EUREKA_INSTANCE_PREFERIPADDRESS
              value: "true"

---
apiVersion: v1
kind: Service
metadata:
  name: eureka
  namespace: ams-backend
  labels:
    app: eureka
spec:
  ports:
  - nodePort: 31300
    port: 8761
  selector:
    app: eureka
  type: NodePort
  
