# eureka
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eureka
  namespace: ams-backend
spec:
  serviceName: "eureka"
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
      - name: eureka
        image: sipacademy2024/serviceregistry
        imagePullPolicy: Always
        ports:
        - containerPort: 8761
        resources:
          limits:
            cpu: "0.2"
            memory: "200Mi"
        env:
        - name: EUREKA_SERVER_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: eureka-cm
              key: eureka_service_address

---
apiVersion: v1
kind: Service
metadata:
  name: eureka
  labels:
    app: eureka
spec:
  clusterIP: None
  ports:
  - port: 8761
    name: eureka
  selector:
    app: eureka

