---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: ams-database
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - env:
        - name: PMA_HOST
          value: "mysql-svc"
        - name: PMA_PORT
          value: "3306"
        image: phpmyadmin/phpmyadmin
        name: phpmyadmin
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-svc
  namespace: ams-database
spec:
  ports:
  - nodePort: 31008
    port: 80
  selector:
    app: phpmyadmin
  type: NodePort
