apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-dynamic
  namespace: ams-database
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
